baseURL: http://example.org/
languageCode: en-us
title: Bruno Prada
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # main:
  #   - identifier: blog
  #     name: Blog
  #     title: Blog
  #     url: /blogs
  #     weight: 1

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/fav_b.png"    
  useBootstrapCDN: false
  animate: true
  theme:
    disableThemeToggle: true
    defaultTheme: "dark" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "Bruno Prada" # Brand name for the brand | default is the title variable
    disableSearch: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false
      disableBLogs: true

  # Hero
  hero:
    enable: true
    intro: 
    title: "Bruno Prada"
    subtitle: "Arquiteto de Solução"
    content: "Profissional da área de Tecnologia da Informação com 8 anos de experiência em Gestão de Projetos de Infraestrutura de TI e 5 anos de experiência em Arquitetura de TI."
    image: "/images/me.png"
    button:
      enable: true
      name: "Currículo"
      url: "https://bit.ly/bhp-curriculo" # todo: substituir link por bit.ly e transformar arquivo em PDF.
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://www.github.com/brunohprada
        # - icon: fab fa-linkedin
        #   url: https://www.github.com/brunohprada

  # About
  about:
    enable: true
    title: "Sobre mim"
    image: "/images/me.png"
    content: |
      Sou **Bruno Prada**, tenho 34 anos e atuo na área de tecnologia há 12 anos. Tenho experiência em **Gestão de Projetos de Infraestrutura de TI** e atualmente sou **Arquiteto de Soluções** no **Setor Financeiro**.
    skills:
      enable: true
      title:
      items:
        - Microsoft Vísio
        - Microsoft Project
        - Microsoft Office
        - Git
        - Atlasian Jira
        - Atlasian Bitbucket
        - Atlasian Confluence
        - HOPEX Platform

  # Experience
  experience:
    enable: true
    title: "Experiência"
    items:
      - job: "Arquiteto de Solução Senior"
        company: "Bradesco Arquitetura"
        companyUrl: "https://banco.bradesco"
        date: "Junho 2017 - Presente"
        info:
          enable: false
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://banco.bradesco"
        content: |
          Análise e Definição de Arquiteturas de Referência para Negócio, Aplicação, Infraestrutura e Dados. Análise de Requisitos Funcionais e Não Funcionais para desenvolvimento de soluções. Análise de novos produtos e ferramentas de TI em Provas de Conceito. Documentação de Arquitetura e Liderança de Equipe de Arquitetura em projetos de grande porte.

          Liderança de Arquitetura para o projeto Open Finance onde contribuí com as definições e direcionamentos de Arquitetura para nuvem pública, definição de processos de validação de proposta de solução arquitetural, nivelamento e padronização de diagramas de arquitetura com Modelagem C4 e MDL 2.0, implementação de registro de decisão arquitetural (ADR). Atuei como Arquiteto de Solução no desenvolvimento de documentação das arquiteturas de Aplicação e de Infraestrutura para um novo motor de crédito baseado em processamento em lote e eventos próximos do tempo real. Atuei no desenvolvimento e documentação de solução de arquitetura para atendimento de requisitos regulatórios para a Lei Geral de Proteção de Dados (LGPD), onde catalogação de dados e integração com serviços de alta plataforma (Mainframe) foram amplamente trabalhados para o sucesso do projeto. Trabalhei em projetos menores que envolviam manutenção arquitetural (AS-IS / TO-BE).

          O projeto Open Finance conquistou 3 prêmios no Open Summit Awards 2022 (1º lugar na categoria Radar Open Finance - Disponibilidade das APIs, 3º lugar na categoria Case Pessoa Jurídica, e 3º lugar na categoria Iniciação de Pagamentos). O projeto de Motor de Crédito apresentou resultados importantes e teve seu retorno de investimento em menos de 1 ano de uso da nova plataforma. Por fim, o projeto LGPD atendeu todos os requisitos regulatórios e promoveu integração com os diversos Canais e empresas ligadas à Organização. 

      - job: "Coordenador de Projetos de Infraestrutura Pleno"
        company: "Bradesco Infraestrutura"
        companyUrl: "https://banco.bradesco"
        date: "Janeiro 2011 - Maio 2017"
        info:
          enable: false
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://banco.bradesco"
        content: |
          Coordenação de projetos de pequeno, médio e grande porte na área de Infraestrutura de TI, planejamento de Recursos Tecnológicos e Pessoas, gerenciamento de tempo, negociação com Stakeholders, gerenciamento de problemas, posicionamentos e relatórios Executivos.

          Acompanhamento e Entrega de infraestrutura para implementação de Ambiente de Contingência Ativo / Passivo e Ativo / Ativo para os Canais de Internet do Banco, infraestrutura para implementação de nova versão do Canal de Internet Pessoa Jurídica (Identidade Visual Renovada e Novas Funcionalidades), infraestrutura para o Portal Comercial do Bradesco Financiamentos (Operadores e Correspondentes), infraestrutura para implementação do Site Institucional do Banco Bradesco (Identidade Visual Renovada) e novo endereço banco.bradesco (top level domain).

          Todos os projetos promoveram atualização tecnológica do parque de servidores do Banco e/ou redução espaço físico com a implementação de servidores virtualizados e/ou aumento dos indicadores de disponibilidade dos ambientes. Do ponto de vista dos Usuários e Clientes, esses projetos promoveram uma melhor experiência de uso dos produtos do Banco Bradesco, o que naturalmente foi convertido em receita para a Organização.

      - job: "Analista de Infraestrutura Estágio"
        company: "Bradesco Infraestrutura"
        companyUrl: "https://banco.bradesco"
        date: "Fevereiro 2010 - Dezembro 2010"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          Documentação de projetos de infraestrutura, atualização de cronogramas de projetos, preparação de posicionamentos e relatórios Executivos e registro de reuniões.

          Contribuição para documentação e atualização de grande projeto chamado Nova Arquitetura de Sistemas que na época visava a atualização dos modelos arquiteturais, definições tecnológicas e separação de domínios para atendimento de negócio no modelo SOA (Service-Oriented Architecture) de todo o Banco Bradesco.

          Ao fim do contrato de estágio, recebi a efetivação ao cargo de Analista de Infraestrutura Junior.

  # Education
  education:
    enable: true
    title: "Educação"
    index: false
    items:
      - title: "Formação de Gestão de Projetos"
        school:
          name: "FIA - Fundação Instituto de Administração"
          url: "https://fia.com.br"
        date: "2012"
        content:
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      - title: "Bacharel em Sistemas de Informação"
        school:
          name: "Universidade Estácio de Sá"
          url: "https://estacio.br/"
        date: "2010"
        content:
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"

  # Contact
  contact:
    enable: true
    title: "Contato"
    content: |
      Estou disponível para conversar. Caso tenha alguma questão, retornarei o mais breve possível.
    email: brunohprada@hotmail.com
    btnName: Me envie um email
      # formspree:
      #   enable: true # `contact.email` value will be ignored
      #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      #   emailCaption: "Enter your email address"
      #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 2
      title: Recent Posts
      enable: false
      disableFeaturedImage: true
    socialNetworks:
      github: https://github.com/brunohprada
      linkedin: https://linkedin.com/brunohprada

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false
    
  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
